In [1]:
import pandas as pd

In [5]:
pd.read_excel('Bawang Merah 2016-2017.xlsx')

,Perkembangan Harga Pangan,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 486,Unnamed: 487,Unnamed: 488,Unnamed: 489,Unnamed: 490,Unnamed: 491,Unnamed: 492,Unnamed: 493,Unnamed: 494,Unnamed: 495
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Periode,NaN,01 Januari 2016 - 31 Desember 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Komoditas,NaN,Bawang Merah (kg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tipe Laporan,NaN,Laporan Harian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,No.,Provinsi,01/01/2016,04/01/2016,05/01/2016,06/01/2016,07/01/2016,08/01/2016,11/01/2016,12/01/2016,...,14/12/2017,15/12/2017,18/12/2017,19/12/2017,20/12/2017,21/12/2017,22/12/2017,27/12/2017,28/12/2017,29/12/2017
6,I,SEMUA PROVINSI,-,-,-,-,-,-,-,-,...,26350,26400,26300,26350,26350,26450,25950,26450,26450,26400
7,II,ACEH,-,-,-,-,-,-,-,-,...,28600,28400,28900,28900,28750,29100,29400,29100,28500,28650
8,III,SUMATERA UTARA,-,-,-,-,-,-,-,-,...,26250,26250,26250,26150,26750,25750,25750,25500,24650,24650
9,IV,SUMATERA BARAT,-,-,-,-,-,-,-,-,...,21900,22250,21500,20900,22650,23000,23000,23500,25250,26500
10,V,RIAU,-,-,-,-,-,-,-,-,...,24900,24900,24400,24400,24250,24250,24250,25850,26150,26050
11,VI,KEPULAUAN RIAU,-,-,-,-,-,-,-,-,...,33350,33100,31000,31000,31500,30950,30950,31550,31700,31700
12,VII,JAMBI,-,-,-,-,-,-,-,-,...,22400,22400,20900,20900,20900,20900,20900,20650,22750,22750
13,VIII,BENGKULU,-,-,-,-,-,-,-,-,...,21500,22500,22500,21500,21500,21500,21500,25500,25500,25500
14,IX,SUMATERA SELATAN,-,-,-,-,-,-,-,-,...,27400,27400,27400,26900,26900,26900,26900,26900,26900,26900
15,X,KEPULAUAN BANGKA BELITUNG,-,-,-,-,-,-,-,-,...,29650,29650,28900,27950,28900,29150,29150,28650,28650,28900
16,XI,LAMPUNG,-,-,-,-,-,-,-,-,...,19500,19500,19250,19000,19000,19000,19000,18750,18500,18650
17,XII,BANTEN,-,-,-,-,-,-,-,-,...,24100,23750,23750,23900,24000,24100,23900,23350,23900,23900
18,XIII,JAWA BARAT,-,-,-,-,-,-,-,-,...,24150,23900,23350,23400,23350,23550,23500,23100,23000,22800
19,XIV,DKI JAKARTA,-,-,-,-,-,-,-,-,...,29000,29000,28250,28250,28500,29000,29000,28250,28250,28250
20,XV,JAWA TENGAH,-,-,-,-,-,-,-,-,...,19800,19250,19400,19450,19500,19500,19650,19750,19500,19650
21,XVI,DI YOGYAKARTA,-,-,-,-,-,-,-,-,...,25750,25250,25750,25750,25750,25750,25750,25500,25000,25000
22,XVII,JAWA TIMUR,-,-,-,-,-,-,-,-,...,19950,20050,20700,20500,20650,20650,20450,20000,20150,20100
23,XVIII,BALI,-,-,-,-,-,-,-,-,...,21200,21350,21450,20500,20750,20900,20500,20250,20500,20650
24,XIX,NUSA TENGGARA BARAT,-,-,-,-,-,-,-,-,...,17700,17700,17700,18250,18250,19350,18250,18250,18250,17650
25,XX,NUSA TENGGARA TIMUR,-,-,-,-,-,-,-,-,...,23150,23150,23150,23150,23150,23150,23150,23150,23150,23150
26,XXI,KALIMANTAN BARAT,-,-,-,-,-,-,-,-,...,26750,26650,26750,27000,27000,27000,27150,27150,27650,27500
27,XXII,KALIMANTAN SELATAN,-,-,-,-,-,-,-,-,...,23250,23250,22900,22900,22900,22900,22900,22400,22400,21750
28,XXIII,KALIMANTAN TENGAH,-,-,-,-,-,-,-,-,...,25500,25250,25000,25000,24900,24900,24750,24750,24750,24750
29,XXIV,KALIMANTAN TIMUR,-,-,-,-,-,-,-,-,...,27650,27850,27650,27850,27650,27650,27250,27100,27100,27150
30,XXV,KALIMANTAN UTARA,-,-,-,-,-,-,-,-,...,28750,28750,30500,30500,28750,28750,30000,30000,30000,31500
31,XXVI,GORONTALO,-,-,-,-,-,-,-,-,...,27000,27000,28000,27000,27000,27000,27000,28000,28000,27000
32,XXVII,SULAWESI SELATAN,-,-,-,-,-,-,-,-,...,23350,22900,23100,24100,23900,23950,24200,24850,24100,23100
33,XXVIII,SULAWESI TENGGARA,-,-,-,-,-,-,-,-,...,28750,28750,28400,28400,28400,28750,28400,28400,28400,28400
34,XXIX,SULAWESI TENGAH,-,-,-,-,-,-,-,-,...,27500,27500,26500,26500,26500,27000,27000,26750,27000,27000
35,XXX,SULAWESI UTARA,-,-,-,-,-,-,-,-,...,27500,28000,29000,29000,29000,29000,29000,29500,29500,29500
36,XXXI,SULAWESI BARAT,-,-,-,-,-,-,-,-,...,26000,26250,26250,25650,25650,25650,25650,25750,22250,22750
37,XXXII,MALUKU,-,-,-,-,-,-,-,-,...,31900,31900,31900,31900,31900,31900,31900,32500,32500,32000
38,XXXIII,MALUKU UTARA,-,-,-,-,-,-,-,-,...,36250,37500,37500,37500,36250,36250,37500,36250,36250,36250
39,XXXIV,PAPUA,-,-,-,-,-,-,-,-,...,38450,38450,38750,38950,39400,38950,38950,38150,38350,38350
40,XXXV,PAPUA BARAT,-,-,-,-,-,-,-,-,...,37500,37500,37500,42500,42500,42500,-,40000,40000,40000